# Training parameters
train:
  episodes: 1000
agent:
  lr: 0.001
  gamma: 0.95
  epsilon: 1.0
  epsilon_min: 0.01
  epsilon_decay: 0.995
  batch_size: 64
  ##DDQN parameters
  alpha: 1e-3
  update_frequency: 10
